'''
'''

import sys
import os
# root project dir
sys.path.append(os.path.abspath("/var/www/project-companies-aggregator"))
from env import * # local env file


COMPLETION_SEED = '''
Given the company's name, country, sector, industry and description, generate tags describing what the company does, works in or is trying to solve.
---
name: Tesla Inc.
country: United States
sector: Capital Goods
Industry: Auto Manufacturing
description: Tesla, Inc. engages in the design, development, manufacture, and sale of fully electric vehicles, energy generation and storage systems. It also provides vehicle service centers, supercharger station, and self-driving capability. The company operates through the following segments: Automotive and Energy Generation and Storage. The Automotive segment includes the design, development, manufacture and sale of electric vehicles. The Energy Generation and Storage segment includes the design, manufacture, installation, sale, and lease of stationary energy storage products and solar energy systems, and sale of electricity generated by its solar energy systems to customers. It develops energy storage products for use in homes, commercial facilities and utility sites. The company was founded by Jeffrey B. Straubel, Elon Reeve Musk, Martin Eberhard, and Marc Tarpenning on July 1, 2003 and is headquartered in Palo Alto, CA.
tags: [
"renewable energy",
"energy generation",
"energy storage systems",
"transition to sustainable energy",
"charging stations",
"electric automotive",
"stationary energy storage products",
"energy storage for utility sites",
"energy storage for commercial sites",
"energy storage for homes",
"electric cars",
"grid services",
"solar energy",
"solar panels",
"climate change",
"green energy",
"ev",
"autonomous driving",
"AI"
]
---
name: Moderna Inc.
country: United States
sector: Health Care
Industry: Biotechnology: Biological Products (No Diagnostic Substances)
description: Moderna, Inc. engages in the development of transformative medicines based on messenger ribonucleic acid (mRNA). Its product pipeline includes the following modalities: prophylactic vaccines, cancer vaccines, intratumoral immuno-oncology, localized regenerative therapeutics, systemic secreted therapeutics, and systemic intracellular therapeutics. The company was founded by Noubar B. Afeyan, Robert S. Langer, Jr., Derrick J. Rose and Kenneth R. Chien in 2010 and is headquartered in Cambridge, MA.
tags:[
"mRNA",
"transformative medicines",
"prophylactic vaccines",
"intratumoral immuno-oncology",
"localized regenerative therapeutics",
"systemic secreted therapeutics",
"systemic intracellular therapeutics",
"drug discovery",
"drug development",
"messenger RNA"
]
---
name: Amazon.com Inc
country: United States
sector: Consumer Services
Industry: Catalog/Specialty Distribution
description: Amazon.com, Inc. engages in the provision of online retail shopping services. It operates through the following business segments: North America, International, and Amazon Web Services (AWS). The North America segment includes retail sales of consumer products and subscriptions through North America-focused websites such as www.amazon.com and www.amazon.ca. The International segment offers retail sales of consumer products and subscriptions through internationally-focused websites. The Amazon Web Services segment involves in the global sales of compute, storage, database, and AWS service offerings for start-ups, enterprises, government agencies, and academic institutions. The company was founded by Jeffrey P. Bezos in July 1994 and is headquartered in Seattle, WA.
tags:[
"e-commerce",
"online retail shopping services",
"cloud",
"web services",
"compute",
"storage",
"database",
"e-readers",
"direct publishing",
"tablets",
"tv",
"smarttv",
"software",
"hardware",
"internet of things"
]
'''.lstrip()


NEW_COMPLETION_REQUEST_INFO = '''
---
name: {name}
country: {country}
sector:  {sector}
Industry: {industry}
description: {description}
tags:[ 
'''.strip()

if __name__ == '__main__':
    if len(sys.argv) > 1:
        ticker_symbol = sys.argv[1]
        print(ticker_symbol)